export * from 'lib/config/naming/iam'
export * from 'lib/config/naming/ecr-repo'
export * from 'lib/config/naming/stacks'
export * from 'lib/config/naming/output-exports'
export * from 'lib/config/naming/ssm-paths'
export * from 'lib/config/naming/tags'
export * from 'lib/config/naming/vpce'
